### ISSUE TITLE
Current DAG Issues

### ISSUE THREAD

**Issue by bransonf** [stlrda/211Dashboard-Workflows#24]
There are a few issues that need to be addressed to properly run the dags in this workflow.

- The `config.py` file doesn't seem to be properly handling the database connections. This was masked in testing by the fact that the database was configured as `postgres_default` (therefore it defaulted in the DAGs)

- psycopg is throwing an error in the `211dash_startup` dag at:
```
[2020-07-07 23:20:31,109] {{taskinstance.py:1145}} ERROR - syntax error at or near "CREATE"
LINE 159: CREATE OR REPLACE VIEW uw211dashboard.public.cre_vu_unemploy...
          ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 175, in run
    cur.execute(s)
psycopg2.errors.SyntaxError: syntax error at or near "CREATE"
LINE 159: CREATE OR REPLACE VIEW uw211dashboard.public.cre_vu_unemploy...
          ^
```

Remaining issues to be added and addressed in this issue.

**Comment by bransonf** [comment]
`psycopg` error due to sql syntax: Fixed.

Config error outstanding, may need to move connection hook to DAGs.

Need to fully review the creation of database tables and views, seems to be a race condition in parallel creation of tables/views, else a wrong dependency on prior DAGs.
